apiVersion: apps/v1
kind: Deployment
metadata:
    name: pre-rt-web
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pre-rt-web
    template:
        metadata:
            labels:
                app: pre-rt-web
        spec:
            containers:
                - name: pre-rt-web
                  image: 'registry.k8s.gu.se/appademin/pre-rt-web:0.0.5'
                  ports:
                      - containerPort: 8080
                        name: web
                        protocol: TCP
                  imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    name: pre-rt-web-service
spec:
    selector:
        app: pre-rt-web
    ports:
        - protocol: TCP
          port: 8080
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
    name: pre-rt-web-route
    annotations:
        kubernetes.io/tls-acme: 'true'
spec:
    host: pre-rt.prod.appadem.in
    to:
        kind: Service
        name: pre-rt-web-service
        weight: 100
    port:
        targetPort: 8080
    tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None
